name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.11
        with:
          heroku_api_key: 421f03d5-0e30-4dd6-b05b-a6ea22e4f1c0
          heroku_app_name: "actions-example"
          heroku_email: "itolvera98@gmail.com"